### ISSUE TITLE
Make releases with the tgz for direct reference

### ISSUE THREAD

**Issue by benmathews** [ohaiwalt/cog-helm#18]
If a release was created, it wouldn't be necessary to clone the repo to use this chart. One could simply say

`helm install https://github.com/ohaiwalt/cog-helm/releases/.... `

**Comment by ohaiwalt** [comment]
Great idea! I haven't dealt with GitHub releases before, but I'll check that out.

**Comment by ohaiwalt** [comment]
Did this manually for now for the current version, I'll look at ways to automate this a bit more in the future. Thanks again for the suggestion!
